name: $(Year:yyyy).$(Month).$(DayOfMonth).$(rev:r)

resources:
- repo: self
  clean: true

trigger:
    branches:
        include:
        - master
        - feature/*
        - bug/*
        exclude:
        - dummy/*
    paths:
        include:
        - /Application
        - /NotificationService

variables:
  - group: 'Authentication'
  - group: 'Release Annotations'

stages:

- stage: Build
  displayName: Build
  
  jobs:

  - template: Pipelines/Build/infrastructure-build-job.yml
    parameters:
      name: Infrastructure
      display_name: 'Infrastructure'
      pool:
        vmImage: 'ubuntu-latest'

  - template: Pipelines/Build/angular-build-job.yml
    parameters:
      name: Angular
      display_name: 'Angular'
      pool:
        vmImage: 'ubuntu-latest'

  - template: Pipelines/Build/azure-function-build-job.yml
    parameters:
      name: 'Azure_Function'
      display_name: 'Azure Function'
      pool:
        vmImage: 'windows-latest'

- stage: Deploy_Azure
  displayName: 'Azure'
  dependsOn: 'Build'  
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  jobs:

  - template: Pipelines/Deploy/infrastructure-deploy-job.yml
    parameters:
      name: Infrastructure
      display_name: 'Infrastructure'
      environment_name: 'Azure'
      pool:
        vmImage: 'ubuntu-latest'

  - template: Pipelines/Deploy/application-deploy-job.yml
    parameters:
      name: Deployment
      display_name: 'Profile Information'
      depends_on: 'Infrastructure'
      environment_name: 'Azure'
      pool:
        vmImage: 'windows-latest'

  - template: Pipelines/Deploy/ui-test-deploy-job.yml
    parameters:
      name: UI_Test
      display_name: 'UI Test'
      depends_on: 'Deployment'
      pool:
        vmImage: 'ubuntu-latest'

  - template: Pipelines/Deploy/stamp-deploy-job.yml
    parameters:
      name: Stamp
      display_name: 'Stamp'
      depends_on: 'UI_Test'
      pool:
        vmImage: 'windows-latest'

  - template: Pipelines/Deploy/performance-deploy-job.yml
    parameters:
      name: Performance
      display_name: 'Performance'
      depends_on: 'Stamp'
      pool:
        vmImage: 'windows-latest'
