name: $(Year:yyyy).$(Month).$(DayOfMonth).$(rev:r)

resources:
- repo: self
  clean: true

trigger:
    branches:
        include:
        - master
        - feature/*
        - bug/*
        exclude:
        - dummy/*
    paths:
        include:
        - /Application
        - /NotificationService

variables:
  - group: 'Authentication'
  - group: 'Release Annotations'

stages:

- stage: Build
  displayName: Build
  
  jobs:

  - template: angular-build-job.yml
    parameters:
      name: Angular
      display_name: 'Angular'
      pool:
        name: 'Hosted Ubuntu 1604'

  - template: azure-function-build-job.yml
    parameters:
      name: 'Azure_Function'
      display_name: 'Azure Function'
      pool:
        name: 'Hosted VS2017'

- stage: Deploy_Azure
  displayName: 'Azure'
  dependsOn: 'Build'  
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  jobs:

  - template: application-deploy-job.yml
    parameters:
      name: Deployment
      display_name: 'Profile Information'
      environment_name: 'Azure'
      pool:
        name: 'Hosted Windows 2019 with VS2019'

  - template: ui-test-deploy-job.yml
    parameters:
      name: UI_Test
      display_name: 'UI Test'
      depends_on: 'Deployment'
      pool:
        name: 'Hosted Ubuntu 1604'

  - template: stamp-deploy-job.yml
    parameters:
      name: Stamp
      display_name: 'Stamp'
      depends_on: 'UI_Test'
      pool:
        name: 'Hosted Ubuntu 1604'

  - template: performance-deploy-job.yml
    parameters:
      name: Performance
      display_name: 'Performance'
      depends_on: 'Stamp'
      pool:
        name: 'Hosted Windows 2019 with VS2019'